Repository anIcedAntFA/blog.ngockhoi96.dev, pull requests merged in 2024-08, with the labels that each got.

#29 🐛 fix(tag): fix and update test, function, resolve eslint error
  .eslintrc.json
  bun.lockb
  package.json
  src/app/global-error.tsx
  src/components/common/card-post/vertical-card-post.tsx
  src/components/common/dialog/__tests__/dialog.test.tsx
  src/components/common/tag/__tests__/hook.test.tsx
  src/components/common/tag/__tests__/tag.test.tsx
  src/components/common/tag/components/tag.tsx
  src/components/common/tag/tag.hook.ts
  src/components/common/tag/tag.module.css
  src/components/common/theme-switcher/theme-switcher.tsx
  src/hooks/__tests__/use-keyboard-commands.test.ts
Labels: testing

#30 🐛 fix(components): fix some bugs, refactor components
  src/app/[locale]/articles/_components/article-view-list/article-view-list.tsx
  src/components/common/card-post/card-post.module.css
  src/components/common/card-post/card-post.type.ts
  src/components/common/card-post/horizontal-card-post.tsx
  src/components/common/language-selector/language-selector.module.css
  src/components/common/language-selector/language-selector.tsx
  src/components/common/menu/components/menu-list.tsx
  src/components/common/menu/components/menu.tsx
  src/components/common/menu/menu.module.css
  src/components/common/menu/menu.type.ts
  src/components/containers/navigation-bar/navigation-bar.tsx
Labels: bug

#31 Feature/create component tabs
  bun.lockb
  package.json
  src/app/[locale]/articles/_components/article-filter-by-view/article-filter-by-view.module.css
  src/app/[locale]/articles/_components/article-filter-by-view/article-filter-by-view.tsx
  src/app/[locale]/articles/_components/article-filter-by-view/index.ts
  src/app/[locale]/articles/_components/article-view-list/article-view-list.module.css
  src/app/[locale]/articles/page.tsx
  src/components/common/card-post/vertical-card-post.tsx
  src/components/common/tabs/components/tab-indicator.tsx
  src/components/common/tabs/components/tab-list.tsx
  src/components/common/tabs/components/tab-panel-group.tsx
  src/components/common/tabs/components/tab-panel.tsx
  src/components/common/tabs/components/tab-trigger.tsx
  src/components/common/tabs/components/tabs.tsx
  src/components/common/tabs/index.ts
  src/components/common/tabs/tabs.config.ts
  src/components/common/tabs/tabs.context.ts
  src/components/common/tabs/tabs.helper.ts
  src/components/common/tabs/tabs.module.css
  src/components/common/tabs/tabs.type.ts
  src/components/common/tag/components/tag-close-trigger.tsx
Labels: feature

#32 Feature/build scroll to top button
  bun.lockb
  src/app/[locale]/layout.tsx
  src/components/common/scroll-to-top-button/index.ts
  src/components/common/scroll-to-top-button/scroll-to-top-button.config.ts
  src/components/common/scroll-to-top-button/scroll-to-top-button.helper.ts
  src/components/common/scroll-to-top-button/scroll-to-top-button.module.css
  src/components/common/scroll-to-top-button/scroll-to-top-button.tsx
  src/components/common/scroll-to-top-button/scroll-to-top-button.type.ts
  src/styles/base/base.css
Labels: feature

#33 🧪 test(components): add test, storybook, fix bugs and refactor scroll…
  src/app/[locale]/articles/page.tsx
  src/components/common/scroll-to-top-button/__stories__/scroll-to-top-button.stories.tsx
  src/components/common/scroll-to-top-button/__tests__/helper.test.ts
  src/components/common/scroll-to-top-button/__tests__/scroll-to-top-button.test.tsx
  src/components/common/scroll-to-top-button/scroll-to-top-button.helper.ts
  src/components/common/scroll-to-top-button/scroll-to-top-button.module.css
  src/components/common/scroll-to-top-button/scroll-to-top-button.tsx
Labels: testing

#34 Feature/build scroll progress bar component
  bun.lockb
  package.json
  src/app/[locale]/articles/_components/article-view-list/article-view-list.tsx
  src/components/common/scroll-progress-bar/index.ts
  src/components/common/scroll-progress-bar/scroll-progress-bar.config.ts
  src/components/common/scroll-progress-bar/scroll-progress-bar.module.css
  src/components/common/scroll-progress-bar/scroll-progress-bar.tsx
Labels: feature

#35 🧪 test(components): add simple test and story book
  bun.lockb
  package.json
  src/components/common/scroll-progress-bar/__stories__/scroll-progress-bar.stories.tsx
  src/components/common/scroll-progress-bar/__tests__/scroll-progress-bar.test.tsx
  src/components/common/scroll-progress-bar/scroll-progress-bar.tsx
  vitest.setup.ts
Labels: testing

#36 🐛 fix(messages,components,styles): add i18n, update tests, styles
  .eslintrc.json
  bun.lockb
  messages/en.json
  messages/vi.json
  package.json
  src/components/common/scroll-progress-bar/__tests__/scroll-progress-bar.test.tsx
  src/components/common/scroll-progress-bar/scroll-progress-bar.tsx
  src/components/common/scroll-to-top-button/__tests__/scroll-to-top-button.test.tsx
  src/components/common/scroll-to-top-button/scroll-to-top-button.tsx
  src/components/common/search-button/search-box/search-box.tsx
  src/components/containers/navigation-bar/navigation-bar.tsx
  src/styles/base/base.css
Labels: bug

#37 🐛 fix(messages, components): update i18n messages
  bun.lockb
  messages/en.json
  messages/vi.json
  src/components/common/github-star-button/github-star-button.tsx
  src/components/common/language-selector/language-selector.tsx
  src/components/common/scroll-progress-bar/scroll-progress-bar.tsx
  src/components/common/scroll-to-top-button/scroll-to-top-button.tsx
  src/components/common/theme-switcher/theme-switcher.tsx
  src/components/containers/navigation-bar/navigation-bar.config.tsx
  src/components/containers/navigation-bar/navigation-bar.tsx
Labels: bug

#38 ✨ feat(layout, navigation-bar): add animation of header when scroll
  src/app/[locale]/layout.tsx
  src/components/containers/navigation-bar/navigation-bar.module.css
  src/components/containers/navigation-bar/navigation-bar.tsx
Labels: feature

#39 Feature/create basic footer
  bun.lockb
  messages/en.json
  messages/vi.json
  package.json
  src/app/[locale]/layout.tsx
  src/components/common/container/container.module.css
  src/components/common/nav-item/index.ts
  src/components/common/nav-item/nav-item.module.css
  src/components/common/nav-item/nav-item.tsx
  src/components/common/scroll-to-top-button/scroll-to-top-button.module.css
  src/components/common/scroll-to-top-button/scroll-to-top-button.tsx
  src/components/containers/footer/footer.config.tsx
  src/components/containers/footer/footer.module.css
  src/components/containers/footer/footer.tsx
  src/components/containers/footer/index.ts
  src/components/containers/navigation-bar/navigation-bar.module.css
  src/components/containers/navigation-bar/navigation-bar.tsx
  src/components/icons/arrow-up-right-icon.tsx
  src/components/icons/discord-icon.tsx
  src/components/icons/facebook-icon.tsx
  src/components/icons/github-icon.tsx
  src/components/icons/linked-in-icon.tsx
  src/styles/base/base.css
  src/styles/themes/dark.css
  src/styles/themes/light.css
Labels: feature

#40 Feature/build table of content
  bun.lockb
  content/articles/cover.jpg
  content/articles/hello-world.mdx
  content/articles/plain.txt
  content/posts/hello-world.mdx
  package.json
  src/app/[locale]/articles/[slug]/page.module.css
  src/app/[locale]/articles/[slug]/page.tsx
  src/app/[locale]/articles/_components/article-view-list/article-view-list.tsx
  src/app/[locale]/posts/[slug]/page.tsx
  src/components/common/container/container.module.css
  src/components/common/link/link.tsx
  src/components/common/mdx-component.tsx
  src/components/common/table-of-content/index.ts
  src/components/common/table-of-content/table-of-content-list.tsx
  src/components/common/table-of-content/table-of-content.helper.ts
  src/components/common/table-of-content/table-of-content.hook.ts
  src/components/common/table-of-content/table-of-content.module.css
  src/components/common/table-of-content/table-of-content.tsx
  src/components/common/table-of-content/table-of-content.type.ts
  src/styles/base/base.css
  src/utils/get-document-height.ts
  velite.config.ts
Labels: feature
